__maestro:
  schema: 2

name: cassandra

ships:
  vagrant-docker: {ip: 10.10.10.30}

services:
  core:
    image: registry.local/core:latest
    instances:
      core:
        ship: vagrant-docker
        ports: {ssh: '22:1000', elasticsearch:  9200, kibana: 80 , consului: 8500}
        volumes:
          /etc/localtime: /etc/localtime
          /etc/timezone: /etc/timezone
        lifecycle:
          running: [{type: tcp, port: consului}]
        dns: [localhost]
  opscenter:
    image: registry.local/opscenter:latest
    requires: [core]
    instances:
      opscenter:
        ship: vagrant-docker
        ports: {ssh: '22:1121', opscenterui: 8888, agent: 61620}
        links:
            core: core
        volumes:
          /etc/localtime: /etc/localtime
          /etc/timezone: /etc/timezone
        lifecycle:
          running: [{type: tcp, port: agent}]
        dns: [localhost]
  cassandra:
    image: registry.local/cassandra:latest
    requires: [core]
    instances:
      cassandra1:
        ship: vagrant-docker
        ports: {ssh: '22:1021', cassandra: 9160, agent: 61621}
        links:
            core: core
        volumes:
          /etc/localtime: /etc/localtime
          /etc/timezone: /etc/timezone
        lifecycle:
          running: [{type: tcp, port: agent}]
        dns: [localhost]
      cassandra2:
        ship: vagrant-docker
        ports: {ssh: '22:1022', agent: "61621:61622"}
        links:
            core: core
        volumes:
          /etc/localtime: /etc/localtime
          /etc/timezone: /etc/timezone
        lifecycle:
          running: [{type: tcp, port: agent}]
        dns: [localhost]
      cassandra3:
        ship: vagrant-docker
        ports: {ssh: '22:1023', agent: "61621:61623"}
        links:
            core: core
        volumes:
          /etc/localtime: /etc/localtime
          /etc/timezone: /etc/timezone
        lifecycle:
          running: [{type: tcp, port: agent}]
        dns: [localhost]
  node:
    image: registry.local/node:latest
    requires: [core]
    instances:
      node1:
        ship: vagrant-docker
        ports: {ssh: '22:1001'}
        links:
            core: core
        volumes:
          /etc/localtime: /etc/localtime
          /etc/timezone: /etc/timezone
          /root/Projects: /home/vagrant/Projects
        lifecycle:
          running: [{type: tcp, port: ssh}]
        dns: [localhost]
