---
- hosts: all
  sudo: yes
  tasks:
    - name: update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600
    - name: make sure joe is installed
      apt: pkg=joe
    - name: make sure htop is installed
      apt: pkg=htop
    - name: make sure pip is installed
      apt: pkg=python-pip
    - name: make sure conntrack is installed
      apt: pkg=conntrack
    - name: configure tmux
      shell: creates=~vagrant/.tmux.conf echo new-session > ~vagrant/.tmux.conf
    - name: force colorful prompt
      lineinfile: dest=~vagrant/.bashrc regexp="^#force_color_prompt" line=force_color_prompt=yes
    - name: add apt_key for docker
      apt_key: url=https://get.docker.io/gpg validate_certs=no
    - name: add repository for docker
      apt_repository: repo='deb http://get.docker.io/ubuntu docker main'
    - name: make sure docker is installed
      apt: pkg=lxc-docker
    - name: add apt_key for nodejs
      apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xc7917b12
    - name: add repository for node
      apt_repository: repo='deb http://ppa.launchpad.net/chris-lea/node.js/ubuntu trusty main'
    - name: make sure nodejs is installed
      apt: pkg=nodejs
    - name: modify docker startup command
      lineinfile: dest=/etc/default/docker regexp="^DOCKER_OPTS=" insertafter="^#DOCKER_OPTS=" line='DOCKER_OPTS="-H tcp://{{ ansible_eth1.ipv4.address }}:4243 -H unix:///var/run/docker.sock"'
      notify: restart docker
    - name: ensure that user vagrant is in docker group
      user: name=vagrant append=yes groups=docker
    - name: install maestro-ng
      pip: name='git+http://github.com/signalfuse/maestro-ng#egg=maestro'
    - name: install weave
      get_url: url=https://raw.githubusercontent.com/zettio/weave/master/weave dest=/usr/local/bin/weave mode=0111 validate_certs=no
    - name: add local docker-registry to hosts-file
      lineinfile: dest=/etc/hosts line="10.10.10.100  registry.local"
  handlers:
    - name: restart docker
      service: name=docker state=restarted
