---
- hosts: all
  sudo: yes
  tasks:
    - name: update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600
    - name: make sure joe is installed
      apt: pkg=joe
    - name: make sure pip is installed
      apt: pkg=python-pip
    - name: make sure python-dev is installed
      apt: pkg=python-dev
    - name: make sure liblzma-dev is installed
      apt: pkg=liblzma-dev
    - name: install docker-registry
      pip: name='docker-registry'
    - name: copy the registry-conf into place
      copy: src=config.yml dest=/usr/local/lib/python2.7/dist-packages/config/config.yml
    - name: copy the init script into place
      copy: src=docker-registry.conf dest=/etc/init/docker-registry.conf
    - name: make sure that the registry is started
      service: name=docker-registry state=started
