# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
ENV["VAGRANT_DEFAULT_PROVIDER"] = "docker"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # plugin conflict
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.define "core" do |app|
    app.vm.provider "docker" do |d,o|
      d.build_dir = "core"
      d.name = "core"
      d.create_args = ["-h","core"]
      d.has_ssh = true
      d.ports = ["9200:9200","80:80","8500:8500"]
      o.ssh.username = "root"
    end
  end

  config.vm.define "bare" do |app|
    app.vm.provider "docker" do |d,o|
      d.build_dir = "bare"
      d.create_args = ["-h","bare"]
      #d.link("core")
      d.has_ssh = true
      o.ssh.username = "root"
    end
  end

end
