name: cassandra

ships:
  vagrant-docker: {ip: 10.10.10.30}

services:
  core:
    image: test/core
    instances:
      core:
        ship: vagrant-docker
        ports: {ssh: '22:1000', elasticsearch:  9200, kibana: 80 , consului: 8500}
        lifecycle:
          running: [{type: tcp, port: consului}]
        dns: localhost
  opscenter:
    image: test/opscenter
    requires: [core]
    instances:
      opscenter:
        ship: vagrant-docker
        ports: {ssh: '22:1121', opscenterui: 8888, agent: 61620}
        links:
            core: core
        lifecycle:
          running: [{type: tcp, port: agent}]
        dns: localhost
  cassandra:
    image: test/cassandra
    requires: [core]
    instances:
      cassandra1:
        ship: vagrant-docker
        ports: {ssh: '22:1021', cassandra: 9160, agent: 61621}
        links:
            core: core
        lifecycle:
          running: [{type: tcp, port: agent}]
        dns: localhost
      cassandra2:
        ship: vagrant-docker
        ports: {ssh: '22:1022', agent: "61621:61622"}
        links:
            core: core
        lifecycle:
          running: [{type: tcp, port: agent}]
        dns: localhost
      cassandra3:
        ship: vagrant-docker
        ports: {ssh: '22:1023', agent: "61621:61623"}
        links:
            core: core
        lifecycle:
          running: [{type: tcp, port: agent}]
        dns: localhost
