name: cassandra

ships:
  vagrant-docker: {ip: 10.10.10.30}

services:
  core:
    image: test/core
    instances:
      core:
        ship: vagrant-docker
        ports: {ssh: '22:1000', elasticsearch:  9200, kibana: 80 , consului: 8500}
        lifecycle:
          running: [{type: tcp, port: consului}]
        dns: localhost
  cassandra:
    image: test/cassandra
    requires: [core]
    instances:
      cassandra1:
        ship: vagrant-docker
        ports: {ssh: '22:1021', cassandra: 9160}
        links:
            core: core
        lifecycle:
          running: [{type: tcp, port: cassandra}]
        dns: localhost
      cassandra2:
        ship: vagrant-docker
        ports: {ssh: '22:1022'}
        links:
            core: core
        dns: localhost
      cassandra3:
        ship: vagrant-docker
        ports: {ssh: '22:1023'}
        links:
            core: core
        dns: localhost
