---
- hosts: all
  sudo: yes
  tasks:
    - name: update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600
    - name: make sure joe is installed
      apt: pkg=joe
    - name: configure tmux
      shell: echo new-session > ~vagrant/.tmux.conf
    - name: force colorful prompt
      shell: sed -i -e 's,#force_color_prompt,force_color_prompt,g' ~vagrant/.bashrc
    - name: add repository for webupd8team
      apt_repository: repo='ppa:webupd8team/java'
    - name: automatically accept the JRE license
      shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    - name: install jdk 8
      apt: pkg=oracle-java8-installer
    - name: install wildfly
      script: wildfly-install.sh creates=/opt/wildfly
