---
- hosts: all
  sudo: yes
  tasks:
    - name: update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600
    - name: make sure joe is installed
      apt: pkg=joe
    - name: add apt_key for docker
      apt_key: url=https://get.docker.io/gpg
    - name: add repository for docker
      apt_repository: repo='deb http://get.docker.io/ubuntu docker main'
    - name: make sure docker is installed
      apt: pkg=lxc-docker
    - name: add apt_key for nodejs
      apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xc7917b12
    - name: add repository for node
      apt_repository: repo='deb http://ppa.launchpad.net/chris-lea/node.js/ubuntu saucy main'
    - name: make sure nodejs is installed
      apt: pkg=nodejs
    - name: install pipework
      get_url: url=https://raw2.github.com/jpetazzo/pipework/master/pipework dest=/usr/local/bin/pipework mode=0555